export const REQUEST_START='REQUEST_START';
export const RESPONSE_ERROR='RESPONSE_ERROR';
export const GET_SERVICES_SUCCESS='GET_SERVICES_SUCCESS';
export const GET_MAIN_SERVICES_SUCCESS='GET_MAIN_SERVICES_SUCCESS';
export const GET_PUBLIC_HOLIDAYS_SUCCESS = 'GET_PUBLIC_HOLIDAYS_SUCCESS';
export let GET_COMPANY_WORK_TIME_SUCCESS = 'GET_COMPANY_WORK_TIME_SUCCESS';


