export const REQUEST_START='REQUEST_START';
export const RESPONSE_ERROR='RESPONSE_ERROR';
export const GET_COMPANY_WORK_TIME='GET_COMPANY_WORK_TIME';
export const GET_MAIN_SERVICE='GET_MAIN_SERVICE';
export const ADD_COMPANY_WORK_TIME='ADD_COMPANY_WORK_TIME';
export const EDIT_COMPANY_WORK_TIME='EDIT_COMPANY_WORK_TIME';
export const DELETE_COMPANY_WORK_TIME='DELETE_COMPANY_WORK_TIME';
export const CHANGE_ACTIVE_COMPANY_WORK_TIME='CHANGE_ACTIVE_COMPANY_WORK_TIME';