export const COUNTY_UPDATE_STATE='COUNTY_UPDATE_STATE';
export const COUNTY_GET_START='COUNTY_GET_START';
export const COUNTY_GET_SUCCESS='COUNTY_GET_SUCCESS';
export const COUNTY_GET_CURRENT_SUCCESS='COUNTY_GET_SUCCESS';
export const COUNTY_GET_ERROR='COUNTY_GET_ERROR';

export const COUNTY_GET_STATES='COUNTY_GET_STATES'

export const COUNTY_GET_OF_STATE='COUNTY_GET_OF_STATE'