export const FEEDBACK_GET_START='FEEDBACK_GET_START';
export const FEEDBACK_GET_SUCCESS='FEEDBACK_GET_SUCCESS';
export const FEEDBACK_GET_ERROR='FEEDBACK_GET_ERROR';
export const FEEDBACK_UPDATE_STATE='FEEDBACK_UPDATE_STATE';