export const REQUEST_START='REQUEST_START';
export const RESPONSE_ERROR='RESPONSE_ERROR';
export const GET_MAIN_SERVICE_SUCCESS='GET_MAIN_SERVICE_SUCCESS';
export const ADD_MAIN_SERVICE_SUCCESS='ADD_MAIN_SERVICE_SUCCESS';
export let DELETE_MAIN_SERVICE_SUCCESS = 'DELETE_MAIN_SERVICE_SUCCESS';
export let CHANGE_STATUS_SUCCESS = 'CHANGE_STATUS_SUCCESS';
export let CHANGE_ONLINE_SUCCESS = 'CHANGE_ONLINE_SUCCESS';
export let EDIT_MAIN_SERVICE = 'EDIT_MAIN_SERVICE';

