export const STATE_UPDATE_STATE='STATE_UPDATE_STATE';
export const STATE_GET_START='STATE_GET_START';
export const STATE_GET_SUCCESS='STATE_GET_SUCCESS';
export const STATE_GET_ERROR='STATE_GET_ERROR';

export const STATE_GET_CURRENT_SUCCESS='STATE_GET_CURRENT_SUCCESS';