export const REQUEST_START='REQUEST_START';
export const RESPONSE_ERROR='RESPONSE_ERROR';
export const GET_ZIP_CODES_SUCCESS='GET_ZIP_CODES_SUCCESS';
export const ZIP_CODE_UPDATE_STATE='ZIP_CODE_UPDATE_STATE';